name: PR Build Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: "ca-central-1"
      IMAGE_REPO_NAME: "pharmakart/reminder-svc"
      AWS_ACCOUNT_ID: "719150847619"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install protoc and dependencies
        run: |
          echo "Installing protoc..."
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v29.3/protoc-29.3-linux-x86_64.zip
          unzip protoc-29.3-linux-x86_64.zip -d $HOME/protoc
          echo "$HOME/protoc/bin" >> $GITHUB_PATH

          echo "Installing protoc-gen-go and protoc-gen-go-grpc..."
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate gRPC Code
        run: |
          echo "Generating gRPC code..."
          make proto

      - name: Build Application
        run: |
          echo "Building the application..."
          make build

      - name: Build Docker Image (Without Pushing)
        run: |
          echo "Building the Docker image..."
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_TAG=${COMMIT_HASH:-latest}
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
